apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
spec:
  generators:
  - pullRequest:
      requeueAfterSeconds: 30
      github:
        # The GitHub organization or user.
        owner: Radiodotco
        # The Github repository
        repo: helloworld
  template:
    metadata:
      name: 'hello-world-{{"{{"}}number{{"}}"}}'
    spec:
      source:
        repoURL: 'https://github.com/Radiodotco/helloworld.git'
        targetRevision: '{{"{{"}}head_short_sha{{"}}"}}'
        path: helm/
        helm:
          parameters:
          - name: "release"
            value: "pull-{{"{{"}}head_short_sha{{"}}"}}"
          - name: "ingress.hosts[0]"
            value: "pull-{{"{{"}}head_short_sha{{"}}"}}.hello-world.poolswitch.pw"
          - name: "ingress.tls[0].hosts[0]"
            value: "pull-{{"{{"}}head_short_sha{{"}}"}}.hello-world.poolswitch.pw"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - ApplyOutOfSync=true
        retry:
            limit: 5
