apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
spec:
  generators:
  - pullRequest:
      requeueAfterSeconds: 300
      github:
        # The GitHub organization or user.
        owner: Radiodotco
        # The Github repository
        repo: helloworld
        appSecretName: argocd-repo-creds-github-app-radio-co
  template:
    metadata:
      name: 'hello-world-{{"{{"}}number{{"}}"}}'
    spec:
      source:
        repoURL: 'https://github.com/Radiodotco/helloworld.git'
        targetRevision: '{{"{{"}}head_sha{{"}}"}}'
        path: helm/
        helm:
          parameters:
          - name: "isApplicationSet"
            value: "true"
          - name: "release"
            value: "{{"{{"}}head_sha{{"}}"}}"
          - name: "ingress.hosts[0]"
            value: "pull-{{"{{"}}head_short_sha{{"}}"}}.hello-world.poolswitch.pw"
          - name: "ingress.tls[0].hosts[0]"
            value: "pull-{{"{{"}}head_short_sha{{"}}"}}.hello-world.poolswitch.pw"
          - name: "ingress.tls[0].secretName"
            value: "hello-world-tls"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: hello-world
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ApplyOutOfSync=true
        retry:
            limit: 5
