apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ template "hello-world.name" . }}-{{ .Values.release }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        appver: {{ .Values.release }}
    name: {{ template "hello-world.name" . }}-{{ .Values.release }}
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 80
          targetPort: 80
    selector:
        app: {{ template "hello-world.name" . }}-{{ .Values.release }}
