release: master-37762fa
replicas: 1
image: radiodotco/hello-world
isApplicationSet: false

ingress:
  enabled: true
  paths:
    - /
  hosts:
    - hello-world.poolswitch.pw
  tls:
    - secretName: hello-world-tls
      hosts:
        - hello-world.poolswitch.pw
